<a href="https://colab.research.google.com/github/espinili/Linear-Algebra-58020/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Problem 1
Student A, Student B, and Student C have a total of Php 89 cash in their banks. Student A has 6 less than Student C. Student B has 3 times what Student C has. How much does each student have?





In [13]:
import numpy as np

eq1 = np.array([[1,1,1],[1,0,4],[0,0,5]])
eq2 = np.array([[89],[89],[95]])
abc = np.linalg.inv(eq1).dot(eq2)
print(abc)



[[13.]
 [57.]
 [19.]]


##Problem 2


In [19]:
A = np.array([[3,-1,1],[9,-3,3],[-12,4,-4]])
print(A)
B = np.array([[5],[15],[-20]])
print(B)
inv_A = np.linalg.inv(A)
print(inv_A)
#AA^-1x = BA^-1
X = np.dot(inv_a,b)
print(X)

#It is not answerable because the cause of the error is that it is a singular matrix.
#Inverse property that is used in getting the solution of this cannot be solved by any method because of the error
#Determinant is 0

[[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]
[[  5]
 [ 15]
 [-20]]


LinAlgError: ignored

##Problem 3


```
# This is formatted as code
```



In [9]:
import numpy as np
Eigen = np.array ([[8, 5, 6],[-12, 9, 12],[-3, -3, 5]])
print(Eigen)
A, B = np.linalg.eig(Eigen)
print('The Eigenvalue/s is/are: ', A)
print('The Eigenvector/s is/are: ', B)

[[  8   5   6]
 [-12   9  12]
 [ -3  -3   5]]
The Eigenvalue/s is/are:  [7.57261747+10.48038345j 7.57261747-10.48038345j 6.85476506 +0.j        ]
The Eigenvector/s is/are:  [[ 0.15132089-0.43458115j  0.15132089+0.43458115j  0.4060127 +0.j        ]
 [ 0.83567939+0.j          0.83567939-0.j         -0.73867419+0.j        ]
 [ 0.05191804+0.29527222j  0.05191804-0.29527222j  0.53806517+0.j        ]]
