<a href="https://colab.research.google.com/github/espinili/Linear-Algebra-58020/blob/main/Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
A = np.array([[2,1],[0,1]])
print(A)
inverse = (np.linalg.inv(A))
print(inverse)

[[2 1]
 [0 1]]
[[ 0.5 -0.5]
 [ 0.   1. ]]


In [12]:
B = np.dot(A,inverse)
print(B)

[[1. 0.]
 [0. 1.]]


In [13]:
#Python Programming to Transpose a 3x3 Matrix A = ([[1,2,3],[5,-6,7],[8,9,8]])
A = np.array([[1,2,3],[5,-6,7],[8,9,8]])
print(A)
B = np.transpose(A)
print(B)

[[ 1  2  3]
 [ 5 -6  7]
 [ 8  9  8]]
[[ 1  5  8]
 [ 2 -6  9]
 [ 3  7  8]]


In [15]:
#Python Programming to Inverse a 3x3 Matrix A = ([[1,2,3],[5,-6,7],[8,9,8]])
A = np.array([[1,2,3],[5,-6,7],[8,9,8]])
print(A)
inverse = (np.linalg.inv(A))
print(inverse)

[[ 1  2  3]
 [ 5 -6  7]
 [ 8  9  8]]
[[-0.555  0.055  0.16 ]
 [ 0.08  -0.08   0.04 ]
 [ 0.465  0.035 -0.08 ]]
