<a href="https://colab.research.google.com/github/espinili/Linear-Algebra-58020/blob/main/Matrix_and_its_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
#Create a 1x3 matrix
a = np.array([1,2,3])
print (a)

[1 2 3]


In [11]:
#Addition of Matrix
a = np.array ([[-5,0],[4,1]])
b = np.array ([[6,-3],[2,3]])
print(a+b)

[[ 1 -3]
 [ 6  4]]


In [12]:
#Subtraction of Matrices 1
a = np.array ([[-5,0],[4,1]])
b = np.array ([[6,-3],[2,3]])
print(a-b)

[[-11   3]
 [  2  -2]]


In [14]:
#Subtraction of Matrices 2
b = np.array ([[6,-3],[2,3]])
print(b-b)


[[0 0]
 [0 0]]
