<a href="https://colab.research.google.com/github/espinili/Linear-Algebra-58020/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Question 1


In [ ]:
#Create a Python code that displays a square matrix whose length is 5
import numpy as np

np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

##Question 2


In [ ]:
#Create a Python code that displays a square matrix whose elements below the principal diagonal are zero
np.triu([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

##Question 3

In [ ]:
#Create a Python code that displays a square matrix which is symmetrical

A = np.array ([[1,2,3,4,5],
                           [1,2,3,4,5],
                           [1,2,3,4,5],
                           [1,2,3,4,5],
                           [1,2,3,4,5]])
#prints a square matrix which is symmetrical

print('A square matrix which is symmetrical')
print(A)

A square matrix which is symmetrical
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


##Question 4

In [ ]:
#What is the inverse of matrix C? Show your solution by python coding.

A = np.array([[1,2,3],[2,3,3],[3,4,-2]])
print(A)
inv_A = np.linalg.inv(A)
print(inv_A)

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


##Question 5

In [ ]:
#What is the determinant of the given matrix in Question 4? Show your solution by python coding

A = np.array([[1,2,3],[2,3,3],[3,4,-2]])
print(A)
det_A = np.linalg.det(A)
print(det_A)

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
5.000000000000001


##Question 6

In [ ]:
# Find the roots of the linear equations by showing its python codes 
A = np.array([[5,4,1], [10,9,4],[10,13,15]])
print(A)
InvA = np.linalg.inv(A)
print("\n")
B = np.array([[3,4],[8,8],[19,2]])
print(B)
print("\n")
roots = np.dot(InvA,B)
print(roots)

[[ 5  4  1]
 [10  9  4]
 [10 13 15]]


[[ 3  4]
 [ 8  8]
 [19  2]]


[[ 4.00000000e-01 -2.00000000e+00]
 [-1.66533454e-15  4.00000000e+00]
 [ 1.00000000e+00 -2.00000000e+00]]
