<a href="https://colab.research.google.com/github/espinili/Linear-Algebra-58020/blob/main/Practice_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
w = np.array([[1,-3],[2,-2],[3,1]])

print(w)


[[ 1 -3]
 [ 2 -2]
 [ 3  1]]


In [6]:
x = np.array([[3,2,1],[-1,2,3],[2,-1,1]])
print(x)

[[ 3  2  1]
 [-1  2  3]
 [ 2 -1  1]]


In [7]:
y = np.array([[1,2,0],[0,-1,2]])
print(y)

[[ 1  2  0]
 [ 0 -1  2]]


In [9]:
z = np.array([[0,1],[2,3]])
print(z)

[[0 1]
 [2 3]]


##a.WY


In [32]:
w = np.array([[1,-3],[2,-2],[3,1]])
y = np.array([[1,2,0],[0,-1,2]])
print('Matrix W =', w)
print('Matrix Y =', y)


Matrix W = [[ 1 -3]
 [ 2 -2]
 [ 3  1]]
Matrix Y = [[ 1  2  0]
 [ 0 -1  2]]


In [33]:
WY = np.dot(w,y)
print(WY)

[[ 1  5 -6]
 [ 2  6 -4]
 [ 3  5  2]]


##b.Z+Z

In [17]:
z = np.array([[0,1],[2,3]])
print(z+z)

[[0 2]
 [4 6]]


In [25]:
Z = np.add(z,z)
print(Z)

[[0 2]
 [4 6]]


##c.3X

In [18]:
x = np.array([[3,2,1],[-1,2,3],[2,-1,1]])
print(3*x)

[[ 9  6  3]
 [-3  6  9]
 [ 6 -3  3]]


In [26]:
X = np.multiply(3,x)
print(X)

[[ 9  6  3]
 [-3  6  9]
 [ 6 -3  3]]


##. The product (YW)2 is not defined


In [83]:
w = np.array([[1,-3],[2,-2],[3,1]])
y = np.array([[1,2,0],[0,-1,2]])
WY = np.dot(w,y)
WYWY = np.square(WY,WY)
T = ('THE STATEMENT IS TRUE')
print(T)
print(WYWY)


THE STATEMENT IS TRUE
[[ 1 25 36]
 [ 4 36 16]
 [ 9 25  4]]


##b. WY – X = 

In [77]:
w = np.array([[1,-3],[2,-2],[3,1]])
y = np.array([[1,2,0],[0,-1,2]])
x = np.array([[3,2,1],[-1,2,3],[2,-1,1]])
WY = np.dot(w,y)
T = ('THE STATEMENT IS TRUE')
print(T)
print(WY-x)


THE STATEMENT IS TRUE
[[-2  3 -7]
 [ 3  4 -7]
 [ 1  6  1]]


##c. YW – Z2 =

In [81]:
w = np.array([[1,-3],[2,-2],[3,1]])
y = np.array([[1,2,0],[0,-1,2]])
z = np.array([[0,1],[2,3]])
YW = np.dot(y,w)
ZZ = np.square(z)
T = ('THE STATEMENT IS TRUE')
print(T)
print(YW-ZZ)


THE STATEMENT IS TRUE
[[ 5 -8]
 [ 0 -5]]
