<a href="https://colab.research.google.com/github/espinili/Linear-Algebra-58020/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

##Question 1


##matrix "C"


In [53]:
C = np.diag([1,1,1,1])
print (C)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


##Question 2

In [54]:
C = np.diag([1,1,1,1])
double = np.multiply(2,C)
print (double)

[[2 0 0 0]
 [0 2 0 0]
 [0 0 2 0]
 [0 0 0 2]]


##Question 3

In [18]:
A = np.array([2,7,4])
B = np.array([3,9,8])
equals = np.cross(A,B)
print(equals)

[20 -4 -3]
