<a href="https://colab.research.google.com/github/espinili/Linear-Algebra-58020/blob/main/Python_Exercise_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
A = np.array([[1,1,1],[1,2,2],[1,2,3]])
print(A)
B = np.array([5,6,8])
print(B)

#AA^-1X = BA^-1
X = np.linalg.inv(A).dot(B)
print(X)

[[1 1 1]
 [1 2 2]
 [1 2 3]]
[5 6 8]
[ 4. -1.  2.]
