<a href="https://colab.research.google.com/github/espinili/Linear-Algebra-58020/blob/main/Vector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
#Create a 1x3 matrix
a = np.array([1,2,3])
print (a)

[1 2 3]


In [12]:
#Create a 2 x 3 matrix
b = np.array([[1,2,3],[4,5,6]])#This is an example of rectangular
print(b)

[[1 2 3]
 [4 5 6]]


In [11]:
#Create a 3x3 matrix
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
#Create a constant array with all values are 6
d = np.full((4,4),6)#This is an example of square matrix
print(d)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [15]:
#Create a diagonal matrix
e = np.array([[1,2,3],[4,5,6],7,8,9])
print(e)
e = np.diagonal([[1,2,3],[4,5,6],[7,8,9]])
print(e)

[list([1, 2, 3]) list([4, 5, 6]) 7 8 9]
[1 5 9]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  


In [16]:
#Create an identify matrix
f = np.eye(4)
print (f)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
#Create a zero matrix
g = np.zeros((4,5))
print(g)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [19]:
#Create an empty matrix
h = np.empty((0,5))
print(h)


[]


In [21]:
#Addition of Matrix
i = np.array([[1,2,3],[4,5,6]])
j = np.zeros((2,3))
print(i+j)

[[1. 2. 3.]
 [4. 5. 6.]]


In [23]:
#Subtraction of Matrices
i = np.array([[1,2,3],[4,5,6]])
j = np.array([[-1,2,4],[7,4,2]])
print(i-j)


[[ 2  0 -1]
 [-3  1  4]]
